### ISSUE TITLE
Support for NetMQ 3.3.3.4

### ISSUE THREAD

**Issue by emVdovin** [NetMQ/NetMQ.WebSockets#3]
Hi

Is it possible to update this project to support a latest NetMQ?
I wanted to update myself but seems like there are some missing source files such as a reference to Utils 

Regards,

**Comment by somdoron** [comment]
I will try to update it today...

**Comment by somdoron** [comment]
@emVdovin you can try the latest version, let me know if it is working for you and I will release a new version

**Comment by emVdovin** [comment]
Looks good with my code.

Thanks for updating it

Regards,
Evgeny Vdovin

---

Altyn Consulting Inc.
phone: 778.928.0829
email: evgeny.vdovin@altyn.camailto:evgeny.vdovin@altyn.ca
lync: evgeny.vdovin@altyn.camailto:evgeny.vdovin@altyn.ca

On Sep 28, 2016, at 8:07 AM, Doron Somech <notifications@github.com<mailto:notifications@github.com>> wrote:

@emVdovinhttps://github.com/emVdovin you can try the latest version, let me know if it is working for you and I will release a new version
